baseURL = "http://example.org/"
languageCode = "pt-BR"
title = "Flatbox"
theme = "flatbox"
themesDir = "src/themes"    
archetypeDir = "src/archetypes"
contentDir = "src/content"
dataDir = "src/data"
staticDir = "src/static"
defaultContentLanguage = "pt-BR"
publishDir = "dist"
